#!/bin/bash
### BEGIN INIT INFO
# Provides:          NGames Maple
# Required-Start:    $local_fs $remote_fs $network $syslog redis-server
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NGames PMS
# Description:       NGames Project Management System
### END INIT INFO

### !!!!!!!! 以下内容一定需要自己重新修改填写 !!!!!!!!

# PMS 安装的绝对路径
APP_ROOT="/data/test"
# 运行 PMS 的用户 (无登陆权限)
APP_USER="pms"
# PMS 后端程序的 LOG 和 PID 绝对路径
DATA_PATH="/data"

### !!!!!!!! 以上内容一定需要自己重新修改填写 !!!!!!!!

DAEMON_OPTS="-C $APP_ROOT/config/puma.rb"
WEB_SERVER_PID="$DATA_PATH/pms.pid"
SVN_SERVER="http://ngames-pmp.googlecode.com/svn/trunk/"

NAME="PMS Backend"
DESC="NGames PMS Service"

check_pid(){
  if [ -f $WEB_SERVER_PID ]; then
    PID=`cat $WEB_SERVER_PID`
    STATUS=`ps aux | grep $PID | grep -v grep | wc -l`
  else
    STATUS=0
    PID=0
  fi
}

execute() {
  sudo -u $APP_USER -H bash -l -c "$1"
}

update() {
  cd $APP_ROOT
   if [ `whoami` = root ]; then
     execute "svn co $SVN_SERVER $APP_ROOT/"
     echo "$DESC updated"
   fi
}

upgrade() {
  cd $APP_ROOT
   if [ `whoami` = root ]; then
     execute "svn co $SVN_SERVER $APP_ROOT/"
     compile
     start
     restart
     echo "$DESC upgrade complete"
   fi
}

compile() {
  cd $APP_ROOT
   if [ `whoami` = root ]; then
     execute "rake assets:precompile --trace"
     echo "$DESC compile success"
   fi
}

start() {
  cd $APP_ROOT
  check_pid
  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
    # Program is running, exit with error code 1.
    echo "Error! $DESC $NAME is currently running!"
    exit 1
  else
    if [ `whoami` = root ]; then
      execute "RAILS_ENV=production bundle exec puma $DAEMON_OPTS"
      echo "$DESC started"
    fi
  fi
}

stop() {
  cd $APP_ROOT
  check_pid
  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
    ## Program is running, stop it.
    kill -QUIT `cat $WEB_SERVER_PID`
    
    rm "$WEB_SERVER_PID" >> /dev/null
    echo "$DESC stopped"
  else
    ## Program is not running, exit with error.
    echo "Error! $DESC not started!"
    exit 1
  fi
}

restart() {
  cd $APP_ROOT
  check_pid
  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
    echo "Restarting $DESC..."
    kill -USR2 `cat $WEB_SERVER_PID`    
    echo "$DESC restarted."
  else
    echo "Error, $NAME not running!"
    exit 1
  fi
}

status() {
  cd $APP_ROOT
  check_pid
  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
    echo "$DESC / Puma with PID $PID is running."
  else
    echo "$DESC is not running."
    exit 1
  fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
fi

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  update)
        update
        ;;
  compile)
        compile
        ;;
  upgrade)
        upgrade
        ;;
  reload|force-reload)
        echo -n "Reloading $NAME configuration: "
        kill -HUP `cat $PID`
        echo "done."
        ;;
  status)
        status
        ;;
  *)
        echo "Usage: sudo service pms {start|stop|compile|restart|reload|status|update|upgrade}" >&2
        exit 1
        ;;
esac

exit 0